functions_csv = "data/hagi_functions.csv"
build_target = "hagi"

[decomp_me]
compiler_name = "clang-8.0.0"
default_compile_flags = "-x c++ -O3 -g2 -std=c++1z -fno-rtti -fno-exceptions -Wall -Wextra -fno-strict-aliasing"
