name: Update Progress

on:
  push:
    branches:
      - main

jobs:
  update-progress:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        version: [1.0.0]

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          submodules: true

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install cxxfilt pyyaml protobuf colorama

      - name: Generate report
        run: |
          PYTHONPATH="${PYTHONPATH}:${{ github.workspace }}/tools" python .github/scripts/gen_report.py -o report.json

      - name: Upload report
        uses: actions/upload-artifact@v4
        with:
          name: ${{ matrix.version }}_report
          path: report.json
